version: '3.9'
services:
    db:
        image: redis:7.0-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        command: redis-server --loglevel warning --requirepass simplepass # --save 20 1 
        volumes: 
          - cache:/data
        ports:
          - 6379:6379
volumes:
  cache:
    driver: local